# Makefile для книги "Платёжный стек"
# Требует: latexmk, xelatex, biber

MAIN     := src/main.tex
BUILD    := build
AUX      := $(BUILD)/aux
PDF      := $(BUILD)/main.pdf
RELEASE_FLAG := $(AUX)/release-mode.tex
LATEXMK  := $(shell command -v latexmk 2>/dev/null || { test -x /Library/TeX/texbin/latexmk && echo /Library/TeX/texbin/latexmk; })

.PHONY: pdf release verify env-check doctor clean clean-all watch terms-audit margin-audit prepare-draft prepare-release

pdf: prepare-draft ## Основная сборка (draft)
	$(LATEXMK) $(MAIN)
	@echo "✓  PDF: $(PDF)"

release: prepare-release ## Release-сборка без authoring-notes
	$(LATEXMK) $(MAIN)
	@test "$$(grep -c '^! ' $(AUX)/main.log || true)" -eq 0
	@echo "✓  PDF (release): $(PDF)"

watch: prepare-draft ## Инкрементальная draft-сборка с авто-перекомпиляцией при изменении файлов
	$(LATEXMK) -pvc $(MAIN)

verify: pdf ## Собрать и показать статус
	@grep 'Output written' build/aux/main.log | sed 's/.*(\([0-9]*\) pages.*/Pages: \1/'
	@printf "Errors: "; grep -c '^! ' build/aux/main.log || true
	@printf "Todo items: "; grep -roc '\\todo\(fig\|cite\|check\)' src/parts/ | awk -F: '{s+=$$2} END {print s}'

env-check: ## Проверить latex toolchain и доступность рабочих/резервных шрифтов
	@./scripts/env-check.sh

doctor: env-check ## Алиас для env-check

terms-audit: ## Проверить термины и зависимости определений (CHAPTER=path/to/file.tex)
	@python3 scripts/term_audit.py $(CHAPTER)

margin-audit: ## Показать плотность маргиналий по build/aux/main.log
	@python3 scripts/margin_audit.py

prepare-draft:
	@rm -f $(RELEASE_FLAG)
	@rm -f $(AUX)/main.fdb_latexmk
	@sleep 1
	@touch src/preamble/build-flags.tex

prepare-release:
	@mkdir -p $(AUX)
	@printf '%% auto-generated by make release\n\\paymentsbookreleasetrue\n' > $(RELEASE_FLAG)
	@rm -f $(AUX)/main.fdb_latexmk
	@sleep 1
	@touch src/preamble/build-flags.tex

clean: ## Удалить промежуточные файлы (оставить PDF)
	$(LATEXMK) -c $(MAIN)
	@rm -rf $(AUX)

clean-all: ## Удалить всё включая PDF
	$(LATEXMK) -C $(MAIN)
	@rm -rf $(BUILD)

list: ## Показать список всех .tex файлов
	@find src -name '*.tex' | sort

lint: ## Проверить линтером (ChkTeX)
	@find src -name '*.tex' -exec chktex -q {} \;

fmt: ## Форматировать все .tex файлы (latexindent)
	@find src -name '*.tex' -exec latexindent -l=.latexindent.yaml -s {} -o {} \;

help: ## Показать справку
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}'

.DEFAULT_GOAL := help
